# QTI IPQ Sound Card Support
snd-soc-ipq-objs := ipq.o
snd-soc-ipq-pcm-raw-objs := ipq-pcm-raw.o ipq-pcm-raw-lb-test.o

obj-$(CONFIG_SND_SOC_IPQ) += ipq.o
obj-$(CONFIG_SND_SOC_IPQ_ADSS) += ipq-adss.o
obj-$(CONFIG_SND_SOC_IPQ_MBOX) += ipq-mbox.o
obj-$(CONFIG_SND_SOC_IPQ_PCM_RAW) += snd-soc-ipq-pcm-raw.o
